name: "Setup Python"
description: "Setup the Python Install"

runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.8"
