name: "Setup libudev-dev"
description: "Install libudev-dev"

runs:
  using: "composite"
  steps:
    - name: Install libudev-dev
      if: startsWith(matrix.os, 'ubuntu')
      shell: bash
      run: |
        sudo apt-get install -y libudev-dev
