name: "Checkout Source"
description: "Downloads the Source for esp-rs/rust"

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        repository: esp-rs/rust
        ref: esp-${{ env.release_version }}
        submodules: true
        path: "rust"
