name: "Upload to github releases"
description: "Upload the final built archive to github"

# In addition to uploading the file to the release
# * This also turns a tag into a release if one doesn't exist already
# * doesn't fail if the file is already uploaded to the release
# * Is a lot simpler than upload-release-asset
# * Seems to be more actively maintained
# * Doesn't require the use of octokit/request-action@v2.x / get latest release

runs:
  using: "composite"
  steps:
    - name: Upload Release Asset
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ env.release_version }}
        files: ${{ env.asset_name }}
