name: 'Read Cache'
description: 'Reads in all of the built artifact files prior to create-archive'

runs:
  using: "composite"
  steps:

    - name: Read Artifact - Rustc
      uses: actions/download-artifact@v2
      with:
        name: rustc-${{ env.build_suffix }}.tar.xz

    - name: Read Artifact - Standard Library
      uses: actions/download-artifact@v2
      with:
        name: rust-std-${{ env.build_suffix }}.tar.xz

    - name: Read Artifact - RustFmt
      uses: actions/download-artifact@v2
      with:
        name: rustfmt-${{ env.build_suffix }}.tar.xz

    - name: Read Artifact - Cargo
      if: startsWith(matrix.os, 'windows')
      uses: actions/download-artifact@v2
      with:
        name: cargo-${{ env.build_suffix }}.tar.xz

    - name: Read Artifact - Src
      if: startsWith(matrix.os, 'windows')
      uses: actions/download-artifact@v2
      with:
        name: rust-src-${{ env.rust_version }}-dev.tar.xz
