name: Xtensa Rust | $TARGET_TRIPLE

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: "Xtensa Rust release version to build"
        required: true
        default: '1.73.0.1'
      release_tag:
        description: "Release tag where artifacts will be stored (e.g. v1.73.0.1, untagged-00000)"
        required: true
        default: "untagged-3ecdd54e672f465cad2e"

env:
  TARGET_TRIPLE: aarch64-unknown-linux-gnu

jobs:
  get_release:
    name: Get release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.get_upload_url.outputs.url }}
    steps:
      - uses: octokit/request-action@v2.x
        id: get_release
        with:
          route: GET /repos/esp-rs/rust-build/releases/tags/${{ github.event.inputs.release_tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: get upload url
        id: get_upload_url
        run: |
          url=$(echo "$response" | jq -r '.upload_url')
          echo "::set-output name=url::$url"
        env:
          response: ${{ steps.get_release.outputs.data }}

  build-xtensa-rust:
    name: Build Xtensa Rust for ${{ matrix.os }}
    needs: get_release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-m1-self-hosted]
        include:
          - os: macos-m1-self-hosted
            ASSET_PATH: "build/dist/rust-nightly-$TARGET_TRIPLE.tar.xz"
            ASSET_NAME: "rust-${{ github.event.inputs.release_version }}-$TARGET_TRIPLE.tar.xz"
            ASSET_CONTENT_TYPE: "application/x-tar"
    steps:
      - name: Initialize Podman
        run: |
          podman ps >/dev/null 2>/dev/null || podman machine start
          podman stop rust-linux || echo "ok"
          podman container rm rust-linux || echo "Container name rust-linux is available"
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Build construction container
        run: |
          cd support/rust-build/$TARGET_TRIPLE
          podman build -t ubuntu-builder  .
      - name: Build Rust
        run: |
          podman run -e RELEASE_DESCRIPTION='${{ github.event.inputs.release_version }}' --name rust-linux ubuntu-builder ./build.sh
          mkdir -p build
          podman cp rust-linux:rust/build/dist build/dist
      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.get_release.outputs.upload_url }}
          asset_path: ${{ matrix.ASSET_PATH }}
          asset_name: ${{ matrix.ASSET_NAME }}
          asset_content_type: ${{ matrix.ASSET_CONTENT_TYPE }}
      - name: Clean up
        run: |
          podman container rm rust-linux
          podman machine stop
          rm -rf build
