name: Publish idf-rust-examples image on DockerHub

on:
  workflow_dispatch:
    inputs:
      rust_build_branch:
        description: 'Branch with test scripts'
        required: true
        default: 'main'
      release_version:
        description: 'Release version - long 4 places for tag'
        required: true
        default: '1.62.1.0'
      rust_patch_version:
        description: 'Release patch version for generation - 3 places for tag'
        required: true
        default: '1.62.1'
      rust_minor_version:
        description: 'Release minor version - 2 places for tag'
        required: true
        default: '1.60'

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.rust_build_branch }}
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: support/idf-rust-examples
          push: true
          tags: espressif/idf-rust-examples:latest,espressif/idf-rust-examples:${{ github.event.inputs.release_version }},espressif/idf-rust-examples:${{ github.event.inputs.rust_patch_version }},espressif/idf-rust-examples:${{ github.event.inputs.rust_minor_version }}

