name: Test macOS x86_64 - build of Rust examples

on:
  workflow_dispatch:
    inputs:
      rust_build_branch:
        description: 'Branch with test scripts'
        required: true
        default: 'main'
      toolchain_version:
        description: 'Version of Rust IDF toolchain'
        required: true
        default: '1.62.0.0'

jobs:
  build-idf-rust-examples:
    name: Build IDF Rust Examples for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.rust_build_branch }}
      - uses: ./.github/actions/tools/setup-python
      - uses: ./.github/actions/tools/setup-ninja
      - name: Test Rust toolchain by compiling STD demo
        run: ./test-rust-toolchain.sh --toolchain-version ${{ github.event.inputs.toolchain_version }}
